.TH SECRET 1
.SH NAME
secret \-  Klient/Server application for sending and downloading encrypted message
.SH SYNOPSIS
.B secret
[\fB\-r\fR \fIFILE\fR]
[\fB\-s\fR \fIHOST\fR]
[\fB\-l\fR]
[\fB\-\-help\fR]
.SH DESCRIPTION
.B secret
.TP
Application in server mode is catching incoming icmp packets decrypting file and downloading it into directory. 
.TP
Application in klient mode is enrypting file and sending it in icmp packet.
.SH OPTIONS
.TP
.BR \-r =\fIFILE\fR
Set the path to file
.TP
.BR \-s =\fIHOST\fR
Set the Hostname or IP address of server.
.TP
.BR \-l
Starts the server for listening.
.TP
.BR \-\-help
Writes quick help about arguments.